### ISSUE TITLE
Proposed Method Rename

### ISSUE THREAD

**Issue by rck3225** [BioSystemsGroup/bsg#4]
Method name `bsg.util.CollectionUtils.countType()` is unclear, as it does not actually count the number of types. Instead, it counts the number of objects in the list of the given type. I propose renaming the method from `countType()` to `countObjectsOfType()`.

**Comment by AndroidSim** [comment]
I like the proposed name change. This function can also be overloaded so that we could count the number of objects of type class from an array of different types of objects.

**Comment by gepr** [comment]
This change will go into ^/branches/islj-paccept and will later be merged into ^/trunks/islj.
